Models/Diretorio.cs
using System.Collections.Generic;
using saturnApp.Models;

namespace saturnApp.Models
{
    public class Diretorio : No
    {
        public virtual List<No> Arquivos { get; set; }

        public Diretorio() : base() {}
        public Diretorio(string Nome, Usuario Dono) : base(Nome, Dono) {}
    }
}

Controllers/ArquivoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using saturnApp.Data;
using saturnApp.Models;

namespace saturnApp.Controllers
{
    public class ArquivoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ArquivoController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Arquivo
        public async Task<IActionResult> Index()
        {
            var saturnContext = _context.Arquivo.Include(a => a.Pai);
            return View(await saturnContext.ToListAsync());
        }

        // GET: Arquivo/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arquivo = await _context.Arquivo
                .Include(a => a.Pai)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (arquivo == null)
            {
                return NotFound();
            }

            return View(arquivo);
        }

        // GET: Arquivo/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewData["PaiId"] = id;
            return View();
        }

        // POST: Arquivo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> CreateAjax(int id) // Arquivo arquivo, 
        {
            var arquivos = Request.Form.Files;
            long tamanhoTotal = 0;

            if (arquivos.Count == 0)
            {
                return Content("Arquivo Inválido");
            }
            else
            {
                foreach (var arquivo in arquivos)
                {

                    if (arquivo == null || arquivo.Length == 0)
                    {
                        return Content("Arquivo Inválido");
                    }
                    else
                    {

                        var now = DateTime.Now.Ticks.ToString();

                        var path = Path.Combine(Directory.GetCurrentDirectory(),
                            "wwwroot/files/", now);

                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await arquivo.CopyToAsync(stream);
                        }

                        tamanhoTotal += arquivo.Length;

                        var arquivoDb = new Arquivo();
                        arquivoDb.criacao = DateTime.Now;
                        arquivoDb.Endereco = now;
                        arquivoDb.Tipo = arquivo.ContentType;
                        arquivoDb.Nome = arquivo.FileName;
                        arquivoDb.Tamanho = arquivo.Length;
                        arquivoDb.PaiId = id;

                        _context.Add(arquivoDb);
                        await _context.SaveChangesAsync();
                    }
                }

                string message = $"{arquivos.Count} arquivo(s) { tamanhoTotal } bytes enviados!";
                return Json(message);
            }
        }

        public async Task<IActionResult> Download(int? id)
        {
            if (id == null) {
                return Content("Arquivo Invalido");
            }

            Arquivo arquivo = await _context.Arquivo.
                SingleOrDefaultAsync(a => a.Id == id);

            var path = Path.Combine(
                           Directory.GetCurrentDirectory(),
                           "wwwroot/files/", arquivo.Endereco);

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, arquivo.Tipo, arquivo.Nome);
        }

        // GET: Arquivo/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arquivo = await _context.Arquivo.SingleOrDefaultAsync(m => m.Id == id);
            if (arquivo == null)
            {
                return NotFound();
            }
            ViewData["PaiId"] = new SelectList(_context.Set<No>(), "Id", "Discriminator", arquivo.PaiId);
            return View(arquivo);
        }

        // POST: Arquivo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Endereco,Hash,Tamanho,Tipo,Extensao,Id,Nome,PaiId")] Arquivo arquivo)
        {
            if (id != arquivo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var arquivoOld = await _context.Arquivo
                        .Include(a => a.Pai)
                        .SingleOrDefaultAsync(m => m.Id == id);

                    arquivoOld.Nome = arquivo.Nome;
                    _context.Update(arquivoOld);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArquivoExists(arquivo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Diretorio", new { id = arquivo.PaiId });
            }
            return RedirectToAction("Index", "Diretorio", new { id = arquivo.PaiId });
        }

        // GET: Arquivo/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arquivo = await _context.Arquivo
                .Include(a => a.Pai)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (arquivo == null)
            {
                return NotFound();
            }

            return View(arquivo);
        }

        // POST: Arquivo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var arquivo = await _context.Arquivo.SingleOrDefaultAsync(m => m.Id == id);
            _context.Arquivo.Remove(arquivo);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Diretorio", new { id = arquivo.PaiId });
            //return RedirectToAction(nameof(Index));
        }

        private bool ArquivoExists(long id)
        {
            return _context.Arquivo.Any(e => e.Id == id);
        }
    }
}

Controllers/DiretorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using saturnApp.Data;
using saturnApp.Models;

namespace saturnApp.Controllers
{
    public class DiretorioController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Usuario> _userManager;

        public DiretorioController(ApplicationDbContext context, UserManager<Usuario> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Diretorio/5
        public async Task<IActionResult> Index(long? id)
        {
            if (id == null)
            {
                var user = await GetCurrentUserAsync();
                id = user.DiretorioId;
            }

            var diretorios = _context.Diretorio
                .Where(d => d.PaiId == id).ToListAsync();


            if (diretorios == null)
            {
                //return NotFound();
            }

            ViewData["currentDir"] = await _context.Diretorio
                .Include(d => d.Pai)
                .SingleOrDefaultAsync(m => m.Id == id);

            ViewData["arquivos"] = await _context.Arquivo
                .Where(d => d.PaiId == id).ToListAsync();

            ViewData["diretorios"] = await _context.Diretorio
                .Where(d => d.PaiId == id).ToListAsync();

            return View();
        }

        // GET: Diretorio/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diretorio = await _context.Diretorio
                .Include(d => d.Pai)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (diretorio == null)
            {
                return NotFound();
            }

            return View(diretorio);
        }

        // GET: Diretorio/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewData["PaiId"] = id;
            return View();
        }

        // POST: Diretorio/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Nome,PaiId")] Diretorio diretorio)
        {
            if (ModelState.IsValid)
            {
                _context.Add(diretorio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = diretorio.PaiId });
            }
            return View(diretorio);
        }

        // GET: Diretorio/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diretorio = await _context.Diretorio.SingleOrDefaultAsync(m => m.Id == id);
            if (diretorio == null)
            {
                return NotFound();
            }
            ViewData["PaiId"] = new SelectList(_context.Set<No>(), "Id", "Discriminator", diretorio.PaiId);
            return View(diretorio);
        }

        // POST: Diretorio/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Nome,PaiId")] Diretorio diretorio)
        {
            if (id != diretorio.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(diretorio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DiretorioExists(diretorio.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PaiId"] = new SelectList(_context.Set<No>(), "Id", "Discriminator", diretorio.PaiId);
            return View(diretorio);
        }

        // GET: Diretorio/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diretorio = await _context.Diretorio
                .Include(d => d.Pai)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (diretorio == null)
            {
                return NotFound();
            }

            return View(diretorio);
        }

        // POST: Diretorio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var diretorio = await _context.Diretorio.SingleOrDefaultAsync(m => m.Id == id);
            _context.Diretorio.Remove(diretorio);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Diretorio", new { id = diretorio.PaiId });
        }

        private bool DiretorioExists(long id)
        {
            return _context.Diretorio.Any(e => e.Id == id);
        }

        public IEnumerable<Diretorio> GetDiretorios(int id)
        {            
            var diretorios =  _context.Diretorio.
                Where(d => d.PaiId == id).ToList();
            //var arquivos = await _context.Arquivo.
            //    Where(d => d.PaiId == id).ToListAsync();

            //string nos = JsonConvert.SerializeObject(new {diretorios, arquivos});

            return diretorios;
        }

        // [HttpGet("{id}", Name = "GetTodo")]
        // public IActionResult GetById(long id)
        // {
        //     var item = _context.TodoItems.FirstOrDefault(t => t.Id == id);
        //     if (item == null)
        //     {
        //         return NotFound();
        //     }
        //     return new ObjectResult(item);
        // }

        public IActionResult Browse()
        {
            return View();
        }
        private Task<Usuario> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

    }
}

Views/Diretorio/Create.cshtml
@model saturnApp.Models.Diretorio

@{
    ViewData["Title"] = "Criar";
}

<h2>Criar Novo Diretorio</h2>

<h4>Diretorio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <input type="hidden" value="@ViewBag.PaiId" asp-for="PaiId" />
            <div class="form-group">
                <div class="btn group">
                    <a asp-action="Index" class="btn btn-secondary">Voltar</a>
                    <input type="submit" value="Criar" class="btn btn-warning" />
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Diretorio/Delete.cshtml
@model saturnApp.Models.Diretorio

@{
    ViewData["Title"] = "Apagar";
}

<h2>Apagar Diretorio</h2>

<h3>Tem certeza?</h3>
<div class="text-center">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <div class="btn-group">
            <a asp-action="Index" class="btn btn-secondary">Voltar</a>
            <input type="submit" value="Apagar" class="btn btn-warning" />
        </div>
    </form>
</div>

Views/Diretorio/Details.cshtml
@model saturnApp.Models.Diretorio

@{
    ViewData["Title"] = "Detalhes";
}

<h2>Detalhes de @Html.DisplayFor(model => model.Nome)</h2>

<div class="text-center">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    <div class="btn-group">
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-secondary">Voltar</a>
        <input asp-action="Index" asp-route-id="@Model.PaiId" type="submit" value="Apagar" class="btn btn-warning" />
    </div>
</div>

Views/Diretorio/Edit.cshtml
@model saturnApp.Models.Diretorio

@{
    ViewData["Title"] = "Editar";
}

<h4>Editar @Html.DisplayFor(model => model.Nome)</h4>
<hr />
<div class="text-center">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>       
        <input type="hidden" asp-for="PaiId" />
        <div class="form-group">
            <div class="btn-group">
                <a asp-action="Index" class="btn btn-secondary">Voltar</a>
                <input type="submit" value="Salvar" class="btn btn-warning" />
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Diretorio/Index.cshtml
@model IEnumerable<saturnApp.Models.Diretorio>
@using saturnApp.Models

@{
    var currentDir = (Diretorio)ViewData["currentDir"];
    var arquivos = (List<Arquivo>)ViewData["arquivos"];
    var diretorios = (List<Diretorio>)ViewData["diretorios"];

    ViewData["Title"] = currentDir.Nome;
}

<h2>@currentDir.Nome</h2>

<div class="paradinhaTop">
    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modalNovoDiretorio">
    Novo Diretorio
    </button>
    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modalNovoArquivo">
    Novo Arquivo
    </button>
    <hr>
</div>
<div class="row">
    <!-- IR PARA O PAI -->
    @if (currentDir.PaiId != null) {
        <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
            <div class="card text-center">
                <a asp-action="Index" asp-route-id="@currentDir.PaiId">
                    <img class="card-img-top icon" src="~/icons/upper-folder.svg" alt="Card image cap">
                    <div class="card-body nome text-dark">..</div>
                </a>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-4">
                            <a class="text-muted disabled"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        </div>
                        <div class="col-4">                        
                            <a class="text-muted disabled"><i class="fa fa-search" aria-hidden="true"></i></a>
                        </div>
                        <div class="col-4">                                                
                            <a class="text-muted disabled"><i class="fa fa-trash" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    <!-- DIRETORIOS -->
    @foreach (var item in diretorios) {
        <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
            <div class="card text-center">
                <a asp-action="Index" asp-route-id="@item.Id">
                    <img class="card-img-top icon" src="~/icons/folder.svg" alt="Card image cap">
                    <div class="card-body nome text-dark">@Html.DisplayFor(modelItem => item.Nome)
                    </div>
                </a>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-4">
                            <a class="text-dark" asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        </div>
                        <div class="col-4">                        
                            <a class="text-dark" asp-action="Details" asp-route-id="@item.Id"><i class="fa fa-search" aria-hidden="true"></i></a>
                        </div>
                        <div class="col-4">                                                
                            <a class="text-dark" asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-trash" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    <!-- ARQUIVOS -->
    @foreach (var item in arquivos) {
        <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
            <div class="card text-center">
                <a asp-controller="Arquivo" asp-action="Download" asp-route-id="@item.Id">
                    <img class="card-img-top icon" src="~/icons/file.svg" alt="Card image cap">
                    <div class="card-body nome text-dark">@Html.DisplayFor(modelItem => item.Nome)</div>
                </a>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-4">
                            <a asp-controller="Arquivo" class="text-dark" asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        </div>
                        <div class="col-4">                        
                            <a asp-controller="Arquivo" class="text-dark" asp-action="Details" asp-route-id="@item.Id"><i class="fa fa-search" aria-hidden="true"></i></a>
                        </div>
                        <div class="col-4">                                                
                            <a asp-controller="Arquivo" class="text-dark" asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-trash" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>


<!-- Nova Pasta -->
<div class="modal fade" id="modalNovoDiretorio" tabindex="-1" role="dialog" aria-labelledby="modalNovoDiretorioLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalNovoDiretorioLabel">Nova Pasta</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="/Diretorio/Create/@currentDir.Id" method="post">
                <div class="modal-body">
                    <div class="form-group">
                        <label class="control-label" for="Nome">Nome</label>
                        <input class="form-control" id="Nome" name="Nome" value="" type="text">
                    </div>
                    <input value="@currentDir.Id" id="PaiId" name="PaiId" type="hidden">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <input value="Criar" class="btn btn-warning" type="submit">
                </div>
            </form>
        </div>
    </div>
</div>


<!-- Novo Arquivo -->
<div class="modal fade" id="modalNovoArquivo" tabindex="-1" role="dialog" aria-labelledby="modalNovoArquivoLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalNovoArquivoLabel">Novo Arquivo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" enctype="multipart/form-data" action="/Arquivo/Create/@currentDir.Id">
                <div class="modal-body">
                    <div>
                        <p>Selecionee:</p>
                        <input name="arquivos" id="arquivos" type="file">
                    </div>
                    <input value="@currentDir.Id" nome="id" type="hidden">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <input id="upload" class="btn btn-warning" value="Enviar Arquivos Selecionados" type="button">
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        $(document).ready(function () {
            $("#upload").click(function (evt) {
                var fileUpload = $("#arquivos").get(0);
                var files = fileUpload.files;
                var data = new FormData();
                for (var i = 0; i < files.length; i++) {
                    data.append(files[i].name, files[i]);
                }
                $.ajax({
                    type: "POST",
                    url: "/Arquivo/CreateAjax/@currentDir.Id",
                    contentType: false,
                    processData: false,
                    data: data,
                    success: function (message) {
                        location.reload();
                        //alert(message);
                    },
                    error: function () {
                        console.log(files);
                        alert("Houve um erro ao enviar um ou mais arquivos!");
                    }
                });
            });
        });
    </script>
}